name: Update Playlist

on:
  workflow_dispatch:   # 允许手动触发
  schedule:
    - cron: "0 */6 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Test Step
        run: echo "Hello GitHub Actions"
